<?php
    echo "<br>";
    echo "<br>";
    echo "<h3>学院注册开放控制</h3>";
echo "<table class='table'>";
echo "<tr>
         <td style='width: 55%'>学院名称</td>   
         <td>学院操作</td>   
      </tr>";
    echo "<tr><td>";
    echo $this -> college_name . "</td>";
    echo "<td><input style='margin-right: 5px;' name='status' id='college_".$this -> college_id."' type='checkbox'".$this -> college_check."></td>";
echo "</table>";
    echo "<br>";
    echo "<br>";
    echo "<h4>学科注册开放控制</h4>";

    echo "<table class='table'>";
    echo "<tr>
         <td style='width: 55%'>学科名称</td>   
         <td>学科操作</td>   
         </tr>";

    foreach ($this -> subjectRes as $subject){
        echo "<tr>";
        echo "<td><span>".$subject['subject_name']."</span></td>";
        echo "<td><input style='margin-right: 5px;' name='status' id='subject_".$subject['subject_id']."' type='checkbox'".$subject['open']."></td>";
        echo "</tr>";
    }
    echo "</table>"

    ?>
<!--<link rel="stylesheet" href="css/bootstrap.min.css" />-->
<link href="https://cdn.bootcss.com/bootstrap-switch/4.0.0-alpha.1/css/bootstrap-switch.min.css" rel="stylesheet">
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap-switch/4.0.0-alpha.1/js/bootstrap-switch.min.js"></script>
<script>
    $('[name="status"]').bootstrapSwitch({    //初始化按钮
        onText:"开启",
        offText:"关闭",
        onColor:"success",
        offColor:"info",
        size:"small",
        onSwitchChange:function(event,state){
            var obj = $(this);
            var id = $(obj).attr('id');
            if(state==true){
                console.log("开启" + id);
                $.ajax({
                    type:"POST",
                    url:"/management/systemmanagement/manageregisterswitch",
                    data:{
                        'switch' : 1,
                        'id':id
                    },
                    success:function(result){
                        alert(result);
                        window.location.href='/management/systemManagement/manageRegister';
                    },
                    // error : function(XMLHttpRequest, textStatus, errorThrown){
                    //     $('#returnText').html(errorThrown);
                    // }
                });
            }else{
                console.log("关闭" + id);
                $.ajax({
                    type:"POST",
                    url:"/management/systemmanagement/manageregisterswitch",
                    data:{
                        'switch' : 2,
                        'id':id
                    },
                    success:function(result){
                        alert(result);
                        window.location.href='/management/systemManagement/manageRegister';
                    },
                    // error : function(XMLHttpRequest, textStatus, errorThrown){
                    //     $('#returnText').html(errorThrown);
                    // }
                });
            }
        }
    });
</script>
