<ul id='myTab' class='nav nav-tabs' style='margin-top: 20px;'>
    <?php
        echo "<li><a href='".$this->url("management/default",array("controller"=>"management","action"=>"loadExcel"))."' >一键导入学院用户</a></li>";
    echo "<li class='active' ><a href='".$this->url("management/default",array("controller"=>"teacher","action"=>"showAllTeacher"))."' >学院用户管理</a></li>";
    echo "<li ><a href='".$this->url("management/default",array("controller"=>"systemManagement","action"=>"others"))."' >管理其他用户</a></li>";
    ?>
</ul>
<div style="overflow:auto;overflow-x:hidden;">
    <table class="table">

        <?php
        if ($this->college) {
            echo "<tr><td>学院名</td>
            <td>学院ID</td>
            <td>院长</td><td>院秘书</td>
            <td>电话</td><td>添加人员</td></tr>";
            foreach ($this->college as $item) {
                echo "<tr><td>" . $item['college_name'] . "</td><td>" . $item['college_id'] . "</td><td>" . $item['manager_name']. "</td><td>" . $item['dean_name'] . "</td><td>" . $item['phone'] .  "</td><td><a  class='btn btn-primary' href='/management/teacher/adddean/".$item['college_id']."'>添加或修改</a></td></tr>";
            }
        } else {
           echo "<center>未找到数据，请检查数据库</center>";
        }
        ?>
    </table>
</div>