<?php
// module/Basicinfo/view/basicinfo/basicinfo/add-teachers.phtml
$title = '导师信息录入';
$this->headTitle($title);
use Zend\Session\Container;
$containerRid = new Container("rid");
$ridArr = $containerRid->item;
?>

<link href="/css/add-subject.css" media="screen" rel="stylesheet" type="text/css">
<style type="text/css">
	.row-fluid [class*="span"]{
		margin-left: 0;
	}
	#form-box label{
		width: 110px;
	}
</style>
<div class="row-fluid" id="main">
<div class='span12' id='bread'>
<ul class="breadcrumb">
    <?php
    $role10 =0;
    if(in_array(10,$ridArr)) {
        $role10 = 1;
        echo "<li><a href='" . $this->url("management/default", array('controller'=>'college',"action" => "addCollege")) . "'>添加学院</a> </li>";
    }?>
  <li class="active">添加导师</li>
  <li><a href='<?php echo $this->url("management/default",array('controller'=>'college',"action"=>"addSubject","param1"=>$this->cid));?>'>添加学科</a> <span class="divider">/</span></li>
</ul>
</div>
<h3><?php echo $this->escapeHtml($this->college_name." 导师添加");?></h3>
<div id="form-box">
<?php
$this->form->setAttribute('action',$this->url('management/default',array('controller'=>'college','action'=>'addTeacher','param1'=>$this->cid)));
$this->form->setAttribute('method','POST');
$this->form->prepare();
echo "<input value='".$this->cid."' id='college_id' type='hidden'>";
echo $this->form()->openTag($this->form);
echo "<div class='row'>".$this->formRow($this->form->get("tid"))."</div>";//导师编号
echo "<div class='span6'>";
echo "<div class='row'>".$this->formRow($this->form->get("sid1"))."</div>";//学科编号
echo "<div class='row'>".$this->formRow($this->form->get("full_time1"))."</div>";//全日制否编号
echo "<div class='row'>".$this->formRow($this->form->get("pid11"))."</div>";//方向编号
echo "<div class='row'>".$this->formRow($this->form->get("pid12"))."</div>";//方向编号
echo "<div class='row'>".$this->formRow($this->form->get("pid13"))."</div>";//方向编号
echo "</div><div class='span6'>";
echo "<div class='row'>".$this->formRow($this->form->get("sid2"))."</div>";//学科编号
echo "<div class='row'>".$this->formRow($this->form->get("full_time2"))."</div>";//全日制否编号
echo "<div class='row'>".$this->formRow($this->form->get("pid21"))."</div>";//方向编号
echo "<div class='row'>".$this->formRow($this->form->get("pid22"))."</div>";//方向编号
echo "<div class='row'>".$this->formRow($this->form->get("pid23"))."</div>";//方向编号
echo "</div>";
echo $this->formRow($this->form->get("submit"));
echo $this->form()->closeTag();
?>
</div>
<hr>
<h3>已添加的导师信息</h3>
<table class='table table-hover'>
	<thead>
	<tr>
	<td>学科</td>
    <td>全日制否</td>
	<td>方向</td>
	<td>姓名</td>
	<td colspan="1">操作</td>
</tr></thead>
<?php
$lastSid = "";
$lastPid = "";
$lastFulltime = "";
$flag = 0;
if(!empty($this->profStaffArr)){
//    echo "导师数据不空<br/>";
	foreach ($this->profStaffArr as $key => $profstaff) {
        echo "<tr>";
        echo "<td>";
        if($lastSid!=$profstaff['subject_id']){
            $lastSid = $profstaff['subject_id'];
            $flag = 1;//新学科标识
            echo $profstaff['subject_id']." ".$profstaff['subject_name'];
        }
        else{
            $flag = 0;//和上一个学科一样
        }
        echo "</td>";

        echo "<td>";
        if($lastFulltime!=$profstaff['full_time']||$flag==1){
            $lastFulltime = $profstaff['full_time'];
            $flag2=1;
            $full_time = $profstaff['full_time']==1?'全日制':'非全日制';
            echo $full_time;
        }
        else{
            $flag2 = 0;
        }
        echo "</td>";

        if($lastPid!=$profstaff['profession_id'] || $flag==1 || $flag2==1){
            $lastPid=$profstaff['profession_id'];
            echo "<td>".$profstaff['profession_id']." ".$profstaff['profession_name']."</td>";
        }
        else echo "<td></td>";

        echo "<td>".$profstaff['staff_id']." ".$profstaff['staff_name']."</td>";
        echo "<td><a href='".$this->url(
            'management/default',
            array(
                'controller'=>'college',
                'action'=>'deleteProfStaff',
                'param1'=>$profstaff['prof_id_unique'],
                'param2'=>$profstaff['staff_id'],
                'param3'=>$this->cid,
                )
//                array(
//                    'query'=>array(
//                        'college_id'=>$this->cid,
//                    )
//                )
            )."'>删除</a></td>";
        //echo "<td><a href='".$this->url("basicinfo",array("action"=>"addProfession","id"=>$subject->subject_id))."'>设置导师</a></td>";
        echo "</tr>";
	}
}
else{
	echo "<tr><td colspan='5'>没有数据</td></tr>";
}
echo "";

?>
</table>

</div>
<script type="text/javascript" src="<?php echo $this->basePath('js/management/get-professions.js');?>"></script>
<script>

    //var elem = document.getElementById("d1");
    var subjects1 = document.getElementsByTagName("select")[1];
    var full_time1 = document.getElementsByTagName("select")[2];
    var subjects2 = document.getElementsByTagName("select")[6];
    var full_time2 = document.getElementsByTagName("select")[7];
    var professions11 = document.getElementsByTagName("select")[3];
    var professions12 = document.getElementsByTagName("select")[4];
    var professions13 = document.getElementsByTagName("select")[5];
    var professions21 = document.getElementsByTagName("select")[8];
    var professions22 = document.getElementsByTagName("select")[9];
    var professions23 = document.getElementsByTagName("select")[10];

    subjects1.onchange = getProfessions1;
    full_time1.onchange = getProfessions1;
    subjects2.onchange = getProfessions2;
    full_time2.onchange = getProfessions2;
    professions12.onchange = function(){
        if(this.value===professions11.value){
            alert("方向和学术型第 1 个方向相同，\n两个方向不能相同，请重新选择");
            this.value = "";
        }
    };

    professions13.onchange = function(){
        if(this.value===professions11.value){
            alert("方向和学术型第 1 个方向相同，\n两个方向不能相同，请重新选择");
            this.value = "";
        }
        else if(this.value===professions12.value){
            alert("方向和学术型第 2 个方向相同，\n两个方向不能相同，请重新选择");
            this.value = "";
        }
    };

    professions22.onchange = function(){
        if(this.value===professions21.value){
            alert("方向和专业型第 1 个方向相同，\n两个方向不能相同，请重新选择");
            this.value = "";
        }
    };

    professions23.onchange = function(){
        if(this.value===professions21.value){
            alert("方向和专业型第 1 个方向相同，\n两个方向不能相同");
            this.value = "";
        }
        else if(this.value===professions22.value){
            alert("方向和专业型第 2 个方向相同，\n两个方向不能相同");
            this.value = "";
        }
    };
</script>