<?php
//echo "新表格<br/>";
$this->form->setAttribute('action', $this->url('management/default', array('controller' => 'college', 'action' => 'addProfession', 'param1' => $this->sid)));
$this->form->setAttribute('method', 'POST');
$this->form->prepare();
echo $this->form()->openTag($this->form);
echo "<input type='hidden' value='".$this->cid."' id='college_id' name='college_id'/>";//
echo "<input type='hidden' value='".$this->full_time."' id='full_time' name='full_time'/>";//
//echo $this->formRow($this->form->get("cid"))."</br>";//学院编号
echo $this->formRow($this->form->get("profession_id")) . "</br>";//方向编号
echo $this->formRow($this->form->get("profession_name")) . "</br>";//方向名称
echo $this->formRow($this->form->get("staff_id")) . "</br>";//方向负责人
echo $this->formRow($this->form->get("submit"));
echo $this->form()->closeTag();