<?php
$this->form->setAttribute('action',$this->url('basicinfo/default',array('controller'=>'basicinfo','action'=>'addCollege')));
$this->form->setAttribute('method','POST');
$this->form->prepare();
echo $this->form()->openTag($this->form);
echo "<div class='row'>".$this->formRow($this->form->get("cid"))."</div>";//学院编号
echo "<div class='row'>".$this->formRow($this->form->get("cname"))."</div>";//学院名称
echo "<div class='row'>".$this->formRow($this->form->get("dean"))."</div>";//负责人
echo "<div id='dean-complete-content' class='complete'></div>";
echo "<div class='row'>".$this->formRow($this->form->get("manager"))."</div>";//院科研秘书
echo "<div id='manager-complete-content' class='complete'></div>";
echo "<div class='row'>".$this->formRow($this->form->get("tstu"))."</div>";//总招生数
echo "<div class='row'>".$this->formRow($this->form->get("fstu"))."</div>";//推免数
echo $this->formRow($this->form->get("submit"));
echo $this->form()->closeTag();
?>
<!--<script type="text/javascript" src="--><?php //echo $this->basePath("js/basicinfo/auto-get-staff.js");?><!--"></script>-->
<!--<script type="text/javascript">-->
<!--    alert('ajax的响应页面');-->
<!--    // $('#dean').live('change',getstaff);-->
<!--    $("#dean").change(getStaff);-->
<!--    $("#manager").change(getStaff);-->
<!--</script>-->